### ISSUE TITLE
Pass context as argument

### ISSUE THREAD

**Issue by Bhargav-InfraCloud** [konstructio/dropkick#21]
By convention, context should be used for propagation (of deadlines, cancellations, etc.), and not stored as a field. Please refer to the article:
https://go.dev/blog/context-and-structs

The following can be avoided by passing the context from Cobra command:
https://github.com/konstructio/dropkick/blob/0119c57346cdaeb061e2c063e75a2afb6185740b/internal/digitalocean/client.go#L20 

_Note: Cobra stores context as a field [here](https://github.com/spf13/cobra/blob/3a5efaede9d389703a792e2f7bfe3a64bc82ced9/command.go#L215) which is an exception because the context is generated inside cobra and will be used only in the scope of its functions (i.e., `RunE`, `PreRunE`, etc.), and ends with the scope._ 

WDYT?

**Comment by fharper** [comment]
Thanks for the contribution @Bhargav-InfraCloud 🎉

Our engineering team will give a closer look to your PR on Monday.

**Comment by Bhargav-InfraCloud** [comment]
Thanks! @fharper @patrickdappollonio
